name: Build and Release ReFoldr

on:
  push:
    tags:
      - 'v*'   # Trigger only on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]
        python-version: [3.11]

    env:
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Set architecture env (macOS only)
        if: runner.os == 'macOS'
        run: |
          echo "ARCH=${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Build executable
        run: |
          mkdir -p dist
          if [ "${{ runner.os }}" == "Windows" ]; then
            pyinstaller --onefile refoldr.py --name refoldr.exe
          else
            pyinstaller --onefile refoldr.py --name refoldr
          fi

      - name: Copy .env for release
        run: |
          cp .env-temp dist/.env

      - name: Rename artifact for architecture
        run: |
          ART_NAME="refoldr-${{ runner.os }}-${{ matrix.arch }}"
          if [ "${{ runner.os }}" == "Windows" ]; then
            mv dist/refoldr.exe dist/${ART_NAME}.exe
          else
            mv dist/refoldr dist/${ART_NAME}
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
