name: Build and Release ReFoldr

on:
  push:
    tags:
      - 'v*'   # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11]
        arch: [x64]

    env:
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable
        shell: bash
        run: |
          mkdir -p dist
          if [ "${{ runner.os }}" == "Windows" ]; then
            pyinstaller --onefile refoldr.py --name refoldr.exe
          else
            pyinstaller --onefile refoldr.py --name refoldr
          fi

      - name: Copy .env and README
        shell: bash
        run: |
          cp .env-temp dist/config.env
          cp README.md dist/README.md

      - name: Create zip for release
        shell: bash
        run: |
          cd dist
          if [ "${{ runner.os }}" == "Windows" ]; then
            powershell Compress-Archive -Path refoldr.exe, config.env, README.md -DestinationPath refoldr-Windows.zip
          else
            zip -r refoldr-${{ runner.os }}.zip refoldr config.env README.md
          fi
          cd ..

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
