name: Build and Release ReFoldr

on:
  push:
    tags:
      - 'v*'   # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11]

    env:
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable
        shell: bash
        run: |
          mkdir -p dist
          
          # Build executable
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            pyinstaller --onefile refoldr.py --name refoldr.exe
            EXE_NAME="refoldr.exe"
          else
            pyinstaller --onefile refoldr.py --name refoldr
            EXE_NAME="refoldr"
          fi

      - name: Copy .env and README
        run: |
          cp .env-temp dist/.env
          cp README.md dist/

      - name: Create ZIP for this OS
        shell: bash
        run: |
          cd dist
          ZIP_NAME="refoldr-${{ runner.os }}.zip"
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            powershell Compress-Archive -Path $EXE_NAME, .env, README.md -DestinationPath $ZIP_NAME
          else
            zip -r $ZIP_NAME $EXE_NAME .env README.md
          fi
          cd ..

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/refoldr-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
